[phases.setup]
nixPkgs = ["php82", "composer", "nodejs-20_x"]

[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --optimize-autoloader",
  "php artisan storage:link || true",
  "npm ci",
  "npm run build"
]

[start]
cmd = "chmod +x start.sh && bash start.sh"

